version: '2'

volumes:
  cstar0-data-volume:
    external: true
  cstar1-data-volume:
    external: true
  cstar2-data-volume:
    external: true

networks:
  dc-net:
    driver: bridge

services:
  # Based on
  # https://hub.docker.com/r/clakech/sparkassandra-dockerized/
  # https://hub.docker.com/_/cassandra/
  spark-master:
    container_name: spark-master
    hostname: spark-master
    image: mklein0/docker-sparkcassandra
    networks:
      - dc-net
    environment:
      - SPARK_MASTER_HOST=spark-master
    command: /start-master.sh

  cstar0:
    container_name: cstar0
    hostname: cstar0
    image: mklein0/docker-sparkcassandra
    networks:
      - dc-net
    environment:
      - CASSANDRA_SEEDS=cstar0,cstar1
      - CASSANDRA_HOST=cstar0
      - CASSANDRA_CLUSTER_NAME="MyCStarCluster"
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - cstar0-data-volume:/var/lib/cassandra

  cstar1:
    container_name: cstar1
    hostname: cstar1
    image: mklein0/docker-sparkcassandra
    networks:
      - dc-net
    environment:
      - CASSANDRA_SEEDS=cstar0,cstar1
      - CASSANDRA_HOST=cstar1
      - CASSANDRA_CLUSTER_NAME="MyCStarCluster"
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - cstar1-data-volume:/var/lib/cassandra

  cstar2:
    container_name: cstar2
    hostname: cstar2
    image: mklein0/docker-sparkcassandra
    networks:
      - dc-net
    environment:
      - CASSANDRA_SEEDS=cstar0,cstar1
      - CASSANDRA_HOST=cstar2
      - CASSANDRA_CLUSTER_NAME="MyCStarCluster"
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - cstar2-data-volume:/var/lib/cassandra
